# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindCoronaCenter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindCoronaCenter
	pod 'Alamofire', '~> 5.5'

  target 'FindCoronaCenterTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'FindCoronaCenterUITests' do
    # Pods for testing
	pod 'Alamofire', '~> 5.5'
  end

end
